<div
     style="padding: 20px;
            color: white;
            font-size: 250%;
            text-align: center;
            display: fill;
            border-radius: 5px;
            background-color: #2a2a9fab;
            overflow: hidden;
            font-weight: 700;
            border: 5px solid #bebe0d;"
     >
Predicting Electricity Tariff for Electricity Customers - Classification
</div>

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Load Data</b></p>
</div>

In [ ]:
# Import Libraries
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_spli, GridSearchCV
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report, confusion_matrix
  

from math import sqrt

df = pd.read_csv("/Users/andystorer/Desktop/Grad School-Miami/Classes /Fall 2025/ISA 514/Module 6 - Data Mining/Class Notes and Exercises/energy_data.csv")
# df.head() - preview the data

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Prepare the Data for Modeling</b></p>
</div>

In [8]:
df.columns

Index(['Age', 'MaritalStatus', 'AnnualConsumption', 'DayNightConsumption',
       'IncomeLevel', 'DwellingArea', 'HasChildren', 'SolarRoof',
       'ShiftableLoad', 'RiskAttitude', 'AttitudeSustainability', 'Tariff'],
      dtype='str')

In [9]:
features = ['Age', 'MaritalStatus', 'DayNightConsumption',
       'IncomeLevel', 'DwellingArea', 'HasChildren', 'SolarRoof',
       'ShiftableLoad', 'RiskAttitude', 'AttitudeSustainability', 'Tariff']

In [10]:
target = ['AnnualConsumption']

In [11]:
# Extract Features and Target ('overall_rating') Values into Separate Dataframes
X = df[features]
y = df[target]

In [12]:
# Let us look at a typical row from our features:
X.iloc[2]

Age                             64
MaritalStatus                    6
DayNightConsumption       0.785733
IncomeLevel                      2
DwellingArea                     4
HasChildren                  False
SolarRoof                     True
ShiftableLoad                    2
RiskAttitude                 False
AttitudeSustainability           2
Tariff                    Tariff 2
Name: 2, dtype: object

In [13]:
# create dummy variables for categorical columsn
X = pd.get_dummies(X,drop_first=True)
X.head()

,Age,MaritalStatus,DayNightConsumption,IncomeLevel,DwellingArea,HasChildren,SolarRoof,ShiftableLoad,RiskAttitude,AttitudeSustainability,Tariff_Tariff 2,Tariff_Tariff 3
0,60,4,0.811033,4,3,False,True,3,True,1,False,True
1,43,4,0.464281,1,1,False,False,3,False,1,False,False
2,64,6,0.785733,2,4,False,True,2,False,2,True,False
3,44,6,0.618946,3,1,False,True,3,True,3,False,False
4,19,5,0.281707,2,1,True,False,4,False,2,False,False

In [14]:
# Let us look at a typical row from our features:
y

     AnnualConsumption
0                 4420
1                 4127
2                 4564
3                 3689
4                 5311
..                 ...
995               2514
996               4766
997               4360
998               5345
999               3492

[1000 rows x 1 columns]

In [15]:
# load the required library
from sklearn.model_selection import train_test_split

# split data into training (70%) and testing (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Decision Tree - Build Classifier Using Training Data</b></p>
</div>

In [18]:
# import the library
from sklearn.tree import DecisionTreeClassifier

# initialize the algorithm
dtree=DecisionTreeClassifier(random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Decision Tree - Generate a New Model Using Training Data Only</b></p>
</div>

In [19]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Decision Tree - Predict Using Test Data</b></p>
</div>

In [20]:
y_dtree_pred = dtree.predict(X_test)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Random Forest - Build Classifier Using Training Data</b></p>
</div>

In [21]:
# import Random Forest algorithm
from sklearn.ensemble import RandomForestClassifier

# create a random forest with 10 trees
rforest=RandomForestClassifier(random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Random "Forest - Generate a New Model Using Training Data Only</b></p>
</div>

In [23]:
rforest.fit(X_train,y_train)

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(random_state=50)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Random Forest - Predict Using Test Data</b></p>
</div>

In [24]:
y_rforest_pred=rforest.predict(X_test)

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Evaluate Models</b></p>
</div>

In [26]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix  

# output the evaluation of decision tree
print(accuracy_score(y_test, y_dtree_pred))
print(confusion_matrix(y_test, y_dtree_pred))  
print(classification_report(y_test, y_dtree_pred)) 
print(dtree.feature_importances_)

0.76
[[136  14  15]
 [ 11  68   6]
 [ 17   9  24]]
              precision    recall  f1-score   support

    Tariff 1       0.83      0.82      0.83       165
    Tariff 2       0.75      0.80      0.77        85
    Tariff 3       0.53      0.48      0.51        50

    accuracy                           0.76       300
   macro avg       0.70      0.70      0.70       300
weighted avg       0.76      0.76      0.76       300

[0.07841862 0.15547706 0.08465927 0.09552493 0.04549219 0.07575213
 0.09820413 0.12412493 0.01744327 0.14334873 0.08155474]

In [27]:
# output the evaluation of random forest
print(accuracy_score(y_test, y_rforest_pred))
print(confusion_matrix(y_test, y_rforest_pred))  
print(classification_report(y_test, y_rforest_pred)) 
print(rforest.feature_importances_)

0.79
[[142  12  11]
 [ 12  69   4]
 [ 18   6  26]]
              precision    recall  f1-score   support

    Tariff 1       0.83      0.86      0.84       165
    Tariff 2       0.79      0.81      0.80        85
    Tariff 3       0.63      0.52      0.57        50

    accuracy                           0.79       300
   macro avg       0.75      0.73      0.74       300
weighted avg       0.78      0.79      0.79       300

[0.09491923 0.17461484 0.12213423 0.11626992 0.05422023 0.06245317
 0.11361317 0.0575769  0.04721368 0.1010562  0.05592845]

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Cross Validation - Hyperparameter Tuning</b></p>
</div>

### *Decision Tree*

_______

In [28]:
# get some idea about the default setting
dtree.get_params

In [29]:
# get the depth of the generated tree
dtree.tree_.max_depth

11

In [30]:
from sklearn.model_selection import GridSearchCV

# Create the parameter grid based on the results of random search 
param_grid = {
    'max_depth': [5, 10, 15],
    'min_samples_leaf': [1, 5, 10],
    'min_samples_split': [1, 5, 10],    
}

# Create a based model
dtree_cv = DecisionTreeClassifier()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = dtree_cv, param_grid = param_grid, cv = 5, n_jobs = -1, verbose = 2)

In [31]:
# Fit the grid search to the data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.04s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.2s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=5; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=1, min_samples_split=10; total time=   0.1s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=5, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s

[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=10, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=1; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=1, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=5; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=10, min_samples_split=10; total time=   0.0s
[CV] END max_depth=15, min_samples_leaf=5, min_samples_split=10; total time=   0.0s

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:489: FitFailedWarning:
45 fits failed out of a total of 135.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py", line 1393, in wrapper
    estimator._validate_params()
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/model_selection/_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.74428571 0.74428571        nan 0.73857143 0.73857143
        nan 0.77       0.77              nan 0.72571429 0.73428571
        nan 0.73714286 0.74285714        nan 0.77142857 0.77142857
        nan 0.73285714 0.73285714        nan 0.74285714 0.74142857
        nan 0.77142857 0.77142857]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [1, 5, 10]},
             verbose=2)

In [32]:
grid_search.best_params_

{'max_depth': 10, 'min_samples_leaf': 10, 'min_samples_split': 5}

In [33]:
# initialize the algorithm
dtree_best=DecisionTreeClassifier(random_state=50, max_depth=10, min_samples_leaf=10, min_samples_split=5)

# Generate a new model using training data only
dtree_best.fit(X_train,y_train)

# predict the test data
y_dtree_best_pred = dtree.predict(X_test)

In [34]:
# output the evaluation of decision tree
print(accuracy_score(y_test, y_dtree_best_pred))
print(confusion_matrix(y_test, y_dtree_best_pred))  
print(classification_report(y_test, y_dtree_best_pred)) 
print(dtree_best.feature_importances_)

0.76
[[136  14  15]
 [ 11  68   6]
 [ 17   9  24]]
              precision    recall  f1-score   support

    Tariff 1       0.83      0.82      0.83       165
    Tariff 2       0.75      0.80      0.77        85
    Tariff 3       0.53      0.48      0.51        50

    accuracy                           0.76       300
   macro avg       0.70      0.70      0.70       300
weighted avg       0.76      0.76      0.76       300

[0.00873816 0.22931599 0.05019422 0.         0.02375906 0.0125329
 0.14448185 0.19060587 0.         0.22630803 0.11406391]

### *Random Forest*

_____

In [35]:
# get some idea about the default setting
rforest.get_params

In [36]:
# get the depth of one of the trees in forest
rforest.estimators_[0].tree_.max_depth

13

In [37]:
from sklearn.model_selection import GridSearchCV

# Create the parameter grid based on the results of random search 
param_grid = {
    'n_estimators': [5, 10, 15],
    'max_depth': [10, 15, 20]
}

# Create a based model
rforest_cv = RandomForestClassifier()

# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rforest_cv, param_grid = param_grid, cv = 5, n_jobs = -1, verbose = 2)

In [38]:
# Fit the grid search to the data
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=10, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV] END ......................max_depth=10, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.2s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.2s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.1s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=10, n_estimators=15; total time=   0.2s
[CV] END .......................max_depth=15, n_estimators=5; total time=   0.2s

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV] END .......................max_depth=15, n_estimators=5; total time=   0.2s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.2s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.2s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.2s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=10; total time=   0.2s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.0s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.1s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.1s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=15, n_estimators=15; total time=   0.1s
[CV] END .......................max_depth=20, n_estimators=5; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=10; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s
[CV] END ......................max_depth=20, n_estimators=15; total time=   0.1s

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [10, 15, 20],
                         'n_estimators': [5, 10, 15]},
             verbose=2)

In [39]:
# output the best values for tuning parameters
grid_search.best_params_

{'max_depth': 15, 'n_estimators': 10}

In [40]:
# create a random forest with 10 trees
rforest_best=RandomForestClassifier(random_state=50, n_estimators=15, max_depth = 20)

# learn the model using the training sets
rforest_best.fit(X_train,y_train)

# use the generated model to predict for the testing set
y_rforest_best_pred=rforest_best.predict(X_test)

/opt/anaconda3/envs/ai-dl/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [41]:
# output the evaluation of random forest
print(accuracy_score(y_test, y_rforest_best_pred))
print(confusion_matrix(y_test, y_rforest_best_pred))  
print(classification_report(y_test, y_rforest_best_pred)) 
print(rforest_best.feature_importances_)

0.77
[[147  10   8]
 [ 20  62   3]
 [ 22   6  22]]
              precision    recall  f1-score   support

    Tariff 1       0.78      0.89      0.83       165
    Tariff 2       0.79      0.73      0.76        85
    Tariff 3       0.67      0.44      0.53        50

    accuracy                           0.77       300
   macro avg       0.75      0.69      0.71       300
weighted avg       0.76      0.77      0.76       300

[0.10642592 0.166001   0.12179254 0.11427377 0.06349862 0.07108414
 0.10433909 0.05406709 0.05117696 0.09779941 0.04954145]

<div
     style="padding: 20px;
            color: white;
            font-size: 250%;
            text-align: center;
            display: fill;
            border-radius: 5px;
            background-color: #2a2a9fab;
            overflow: hidden;
            font-weight: 700;
            border: 5px solid #bebe0d;"
     >
Predicting Electricity Tariff for Electricity Customers - Regression
</div>

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Load Libraries</b></p>
</div>

In [1]:
import pandas as pd 
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

<div style="color:white;display:fill;
            background-color:#2a2a9fab;font-size:200%;">
    <p style="padding: 4px;color:white;"><b>Prepare Data for Modeling</b></p>
</div>

In [4]:
df.columns

Index(['Age', 'MaritalStatus', 'AnnualConsumption', 'DayNightConsumption',
       'IncomeLevel', 'DwellingArea', 'HasChildren', 'SolarRoof',
       'ShiftableLoad', 'RiskAttitude', 'AttitudeSustainability', 'Tariff'],
      dtype='str')

In [6]:
features = ['Age', 'MaritalStatus', 'DayNightConsumption',
       'IncomeLevel', 'DwellingArea', 'HasChildren', 'SolarRoof',
       'ShiftableLoad', 'RiskAttitude', 'AttitudeSustainability', 'Tariff']

In [7]:
target = ['AnnualConsumption']